# These are supported funding platforms
# Uncomment and add your username to enable

# github: [your-username]
# patreon: your-patreon-username
# open_collective: your-open-collective-username
# ko_fi: your-ko-fi-username
# buy_me_a_coffee: your-buy-me-a-coffee-username
# custom: ['https://your-custom-link.com']
